version: 0.1
phases:
    install:
        commands:
            - 'sudo yum install npm'
            # - ‘touch .npmignore’
            - ‘sudon npm install -g gatsby@3.15.0’
    pre_build:
        commands:
            - ‘sudo npm install’
    build:
        commands:
            - ‘sudo gatsby build’
    post_build:
        commands:
            - ‘gatsby-plugin-s3 deploy -y’
artifacts:
    base-directory: public
    files:
        - ‘**/*’
    discard-paths: yes