version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - 'touch .npmignore'
            - 'npm install -g gatsby@3.4.1'
            - 'npm install -g gatsby-plugin-s3'
    pre_build:
        commands:
            - 'npm install'
    build:
        commands:
            - 'npm run build'
    post_build:
        commands:       
            - 'gatsby-plugin-s3 deploy -y'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: yes