version: 0.1
phases:
    install:
        commands:
            # - 'sudo yum install npm'
            # - ‘touch .npmignore’
            - 'sudo apt-get update'
            - 'sudo apt-get upgrade -y'
            - 'sudo apt-get install npm'
            - ‘npm install -g gatsby@3.15.0’
    pre_build:
        commands:
            - ‘npm install’
    build:
        commands:
            - ‘npm run build’
    post_build:
        commands:
            - ‘gatsby-plugin-s3 deploy -y’
artifacts:
    base-directory: public
    files:
        - ‘**/*’
    discard-paths: yes