version: 0.1
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - npm install
    build:
        commands:
            - gatsby build
    post_build:
        commands:
            - gatsby-plugin-s3 deploy -y
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: yes
