version: 0.2
env:
  variables:
    NODE_VERSION: "12"
phases:
    install:
        commands:
            - nvm install $NODE_VERSION
            - node -v
            - npm -v
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - gatsby-plugin-s3 deploy -y
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: yes
